[package]
name = "nes-render"
version = "0.1.0"
edition = "2021"

[features]
default = []
headless-cli = ["dep:clap"]
fm2-cli = [
    "headless-cli",
    "nes-core/rewind-disabled",
    "nes-core/timestamped-scheduler",
]
apu-disabled = ["nes-core/apu-disabled"]
rewind-disabled = ["nes-core/rewind-disabled"]
timestamped-scheduler = ["nes-core/timestamped-scheduler"]
headless-render-disabled = ["nes-core/headless-render-disabled"]
layered-render = ["nes-core/layered-render"]

[dependencies]
nes-core = { path = "../nes-core" }
image = "0.24.0"
clap = { version = "4.0.15", features = ["derive"], optional = true }

[[bin]]
name = "headless_test"
path = "src/bin/headless_test.rs"
required-features = ["headless-cli"]

[[bin]]
name = "fm2_to_mp4"
path = "src/bin/fm2_to_mp4.rs"
required-features = ["fm2-cli"]

[[bin]]
name = "capture_png"
path = "src/bin/capture_png.rs"

[[bin]]
name = "probe_inputs"
path = "src/bin/probe_inputs.rs"
