#[derive(Clone, Debug)]
pub(crate) enum Opcode {
    ADC,
    AHX,
    ALR,
    ANC,
    AND,
    ARR,
    ASL,
    AXS,
    BCC,
    BCS,
    BEQ,
    BIT,
    BMI,
    BNE,
    BPL,
    BRK,
    BVC,
    BVS,
    CLC,
    CLD,
    CLI,
    CLV,
    CMP,
    CPX,
    CPY,
    DCP,
    DEC,
    DEX,
    DEY,
    EOR,
    INC,
    INX,
    INY,
    ISB,
    JMP,
    JSR,
    LAS,
    LAX,
    LDA,
    LDX,
    LDY,
    LSR,
    NOP,
    ORA,
    PHA,
    PHP,
    PLA,
    PLP,
    RLA,
    ROL,
    ROR,
    RRA,
    RTI,
    RTS,
    SAX,
    SBC,
    SEC,
    SED,
    SEI,
    SHX,
    SHY,
    SLO,
    SRE,
    STA,
    STP,
    STX,
    STY,
    TAS,
    TAX,
    TAY,
    TSX,
    TXA,
    TXS,
    TYA,
    XAA,
}

#[derive(Clone, Debug)]
pub(crate) enum AddressingMode {
    Implied,
    Accumulator,      // A
    Absolute,         // $xxxx       a
    AbsoluteIndexedX, // $xxxx,Y     a,x ?? $xx,PC
    AbsoluteIndexedY, // $xxxx,Y     a,y $xx,PC
    Immediate,        // #$xx:       #i
    IndexedIndirect,  // ($xx,X)     (d,x) $xx
    Indirect,         // ($xxxx)     (a)
    IndirectIndexed,  // ($xx),Y     (d),y $xx,X
    Relative,         // $xx,PC      *+d
    ZeroPage,         // $xx         d
    ZeroPageIndexedX, // $xx,X       d,x
    ZeroPageIndexedY, // $xx,X       d,y
}

#[derive(Clone, Debug)]
pub(crate) enum AddressInfo {
    Implied,
    Accumulator,
    Absolute {
        address: u16,
    },
    AbsoluteIndexedX {
        indirect: u16,
        address: u16,
    },
    AbsoluteIndexedY {
        indirect: u16,
        address: u16,
    },
    Immediate {
        address: u16,
    },
    IndexedIndirect {
        offset: u8,
        indirect: u16,
        address: u16,
    },
    Indirect {
        indirect: u16,
        address: u16,
    },
    IndirectIndexed {
        offset: u8,
        indirect: u16,
        address: u16,
    },
    Relative {
        offset: u8,
        address: u16,
    },
    ZeroPage {
        address: u8,
    },
    ZeroPageIndexedX {
        offset: u8,
        address: u16,
    },
    ZeroPageIndexedY {
        offset: u8,
        address: u16,
    },
}

#[derive(Clone, Debug)]
pub(crate) struct ExtendedOpcode {
    pub(crate) opcode: Opcode,
    pub(crate) addressing_mode: AddressingMode,
    pub(crate) min_cycles: u8,
    pub(crate) page_boundary_penalty: bool,
}

pub(crate) const EXTENDED_OPCODES: [ExtendedOpcode; 256] = [
    ExtendedOpcode {
        opcode: Opcode::BRK,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ORA,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SLO,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ORA,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ASL,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SLO,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::PHP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ORA,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ASL,
        addressing_mode: AddressingMode::Accumulator,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ANC,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ORA,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ASL,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SLO,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::BPL,
        addressing_mode: AddressingMode::Relative,
        min_cycles: 2,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::ORA,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 5,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SLO,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ORA,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ASL,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SLO,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CLC,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ORA,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SLO,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::ORA,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::ASL,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SLO,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::JSR,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::AND,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RLA,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::BIT,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::AND,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ROL,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RLA,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::PLP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::AND,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ROL,
        addressing_mode: AddressingMode::Accumulator,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ANC,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::BIT,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::AND,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ROL,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RLA,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::BMI,
        addressing_mode: AddressingMode::Relative,
        min_cycles: 2,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::AND,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 5,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RLA,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::AND,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ROL,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RLA,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SEC,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::AND,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RLA,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::AND,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::ROL,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RLA,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RTI,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::EOR,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SRE,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::EOR,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LSR,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SRE,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::PHA,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::EOR,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LSR,
        addressing_mode: AddressingMode::Accumulator,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ALR,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::JMP,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::EOR,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LSR,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SRE,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::BVC,
        addressing_mode: AddressingMode::Relative,
        min_cycles: 2,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::EOR,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 5,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SRE,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::EOR,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LSR,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SRE,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CLI,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::EOR,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SRE,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::EOR,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::LSR,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SRE,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RTS,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ADC,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RRA,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ADC,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ROR,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RRA,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::PLA,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ADC,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ROR,
        addressing_mode: AddressingMode::Accumulator,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ARR,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::JMP,
        addressing_mode: AddressingMode::Indirect,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ADC,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ROR,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RRA,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::BVS,
        addressing_mode: AddressingMode::Relative,
        min_cycles: 2,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::ADC,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 5,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RRA,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ADC,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ROR,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RRA,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SEI,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ADC,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RRA,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::ADC,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::ROR,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::RRA,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STA,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SAX,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STY,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STA,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STX,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SAX,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DEY,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::TXA,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::XAA,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STY,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STA,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STX,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SAX,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::BCC,
        addressing_mode: AddressingMode::Relative,
        min_cycles: 2,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::STA,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::AHX,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STY,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STA,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STX,
        addressing_mode: AddressingMode::ZeroPageIndexedY,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SAX,
        addressing_mode: AddressingMode::ZeroPageIndexedY,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::TYA,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STA,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::TXS,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::TAS,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SHY,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::STA,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SHX,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::AHX,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDY,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDA,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDX,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LAX,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDY,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDA,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDX,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LAX,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::TAY,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDA,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::TAX,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LAX,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDY,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDA,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDX,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LAX,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::BCS,
        addressing_mode: AddressingMode::Relative,
        min_cycles: 2,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::LDA,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 5,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LAX,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 5,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::LDY,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDA,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDX,
        addressing_mode: AddressingMode::ZeroPageIndexedY,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LAX,
        addressing_mode: AddressingMode::ZeroPageIndexedY,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CLV,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LDA,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::TSX,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::LAS,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::LDY,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::LDA,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::LDX,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::LAX,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::CPY,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CMP,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DCP,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CPY,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CMP,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DEC,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DCP,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::INY,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CMP,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DEX,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::AXS,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CPY,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CMP,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DEC,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DCP,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::BNE,
        addressing_mode: AddressingMode::Relative,
        min_cycles: 2,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::CMP,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 5,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DCP,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CMP,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DEC,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DCP,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CLD,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CMP,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DCP,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::CMP,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::DEC,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::DCP,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CPX,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SBC,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ISB,
        addressing_mode: AddressingMode::IndexedIndirect,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CPX,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SBC,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 3,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::INC,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ISB,
        addressing_mode: AddressingMode::ZeroPage,
        min_cycles: 5,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::INX,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SBC,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SBC,
        addressing_mode: AddressingMode::Immediate,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::CPX,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SBC,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::INC,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ISB,
        addressing_mode: AddressingMode::Absolute,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::BEQ,
        addressing_mode: AddressingMode::Relative,
        min_cycles: 2,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::SBC,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 5,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::STP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ISB,
        addressing_mode: AddressingMode::IndirectIndexed,
        min_cycles: 8,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SBC,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 4,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::INC,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ISB,
        addressing_mode: AddressingMode::ZeroPageIndexedX,
        min_cycles: 6,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SED,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::SBC,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::Implied,
        min_cycles: 2,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ISB,
        addressing_mode: AddressingMode::AbsoluteIndexedY,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::NOP,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::SBC,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 4,
        page_boundary_penalty: true,
    },
    ExtendedOpcode {
        opcode: Opcode::INC,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
    ExtendedOpcode {
        opcode: Opcode::ISB,
        addressing_mode: AddressingMode::AbsoluteIndexedX,
        min_cycles: 7,
        page_boundary_penalty: false,
    },
];

#[derive(Clone, Debug)]
pub(crate) struct DecodedInstruction {
    pub(crate) extended_opcode: &'static ExtendedOpcode,
    pub(crate) address_info: AddressInfo,
    pub(crate) final_address: Option<u16>,
    pub(crate) width: u8,
    pub(crate) page_boundary_hit: bool,
}
